Repository Highrachy/ballers-api, pull requests merged in 2020-03, with the labels that each got.

#3 #171566070 intergrate libraries for test & travis
  .eslintrc.js
  .mocharc.js
  README.md
  app.js
  package-lock.json
  package.json
  test/config.js
  test/routes/welcome.test.js
  travis.yml
Labels: Accepted

#4 #171565994 fixed comments from previous PR
  app.js
  config/winston.js
  public/index.html
  routes/welcome.js
Labels: Needs Fix

#5 #171691191 configure database (mongodb)
  .env.sample
  app.js
  config/config.js
  config/winston.js
  package-lock.json
  package.json
Labels: Needs Fix

#7 #171808802 Configure coveralls for ballers
  .babelrc
  .nycrc
  .travis.yml
  README.md
  package-lock.json
  package.json
Labels: Review Required

#8 #171808808 Configure HoundCI for ballers
  .eslintrc
  .eslintrc.js
  .hound.yml
Labels: Review Required

#9 #171808935 create registration endpoint
  .babelrc
  .env.sample
  .eslintrc
  .nycrc
  app.js
  config/config.js
  config/db.js
  models/user.model.js
  package-lock.json
  package.json
  routes/user.js
  services/user.service.js
  test/config.js
  test/model/user.model.test.js
  test/routes/user.test.js
Labels: Accepted

#10 #171808964 Create Staging/Production Environment for Ballers API
  .gitignore
  .nycrc
  package.json
  server/config/config.js
  server/config/db.js
  server/config/winston.js
  server/index.js
  server/models/user.model.js
  server/routes/user.js
  server/routes/welcome.js
  server/services/user.service.js
  test/config.js
  test/model/user.model.test.js
  test/routes/welcome.test.js
Labels: Accepted

#11 #172016511 Refactor linting in the codebase
  .eslintrc
  .prettierrc
  package-lock.json
  package.json
  server/config/winston.js
  server/models/user.model.js
  server/routes/user.js
  test/config.js
  test/routes/user.test.js
Labels: Accepted

#12 #171691121 configure swagger documentation
  package-lock.json
  package.json
  server/index.js
  server/models/user.model.js
  server/routes/user.js
  test/server/config.js
  test/server/model/user.model.test.js
  test/server/routes/user.test.js
  test/server/routes/welcome.test.js
Labels: Accepted
